import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#7200c2",
        "primary-container": "#8e2de2",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#ddb7ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#f1dcff",
        "on-primary-fixed": "#2c0050",
        "on-primary-fixed-variant": "#6900b3",
        secondary: "#5f5e60",
        "secondary-container": "#e2dfe1",
        "secondary-fixed": "#e4e2e4",
        "secondary-fixed-dim": "#c8c6c8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#636264",
        "on-secondary-fixed": "#1b1b1d",
        "on-secondary-fixed-variant": "#474649",
        tertiary: "#734100",
        "tertiary-container": "#955600",
        "tertiary-fixed": "#ffdcbe",
        "tertiary-fixed-dim": "#ffb872",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffddc1",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3c00",
        background: "#fff7fe",
        "on-background": "#1f1924",
        surface: "#fff7fe",
        "surface-bright": "#fff7fe",
        "surface-dim": "#e1d6e5",
        "surface-container": "#f6eaf9",
        "surface-container-low": "#fbf0ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f0e4f3",
        "surface-container-highest": "#eadfed",
        "surface-variant": "#eadfed",
        "surface-tint": "#8621da",
        "on-surface": "#1f1924",
        "on-surface-variant": "#4d4354",
        "inverse-surface": "#342e39",
        "inverse-on-surface": "#f9edfc",
        "inverse-primary": "#ddb7ff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#7e7386",
        "outline-variant": "#cfc2d7",
      },
      borderRadius: {
        bento: "24px",
        "bento-sm": "16px",
      },
      spacing: {
        gutter: "24px",
        margin: "48px",
        "container-max": "1440px",
        unit: "8px",
      },
      fontFamily: {
        inter: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
